INSERT INTO doctors (name)
VALUES 
    ('Dr. John Smith'),
    ('Dr. Emily Johnson'),
    ('Dr. Michael Davis'),
    ('Dr. Sarah Wilson'),
    ('Dr. David Brown'),
    ('Dr. Jennifer Miller'),
    ('Dr. James Anderson'),
    ('Dr. Jessica Thomas'),
    ('Dr. Daniel Martinez'),
    ('Dr. Samantha Taylor'),
    ('Dr. Christopher Lee'),
    ('Dr. Amanda Clark'),
    ('Dr. Matthew Hall'),
    ('Dr. Elizabeth Young'),
    ('Dr. Benjamin Lewis'),
    ('Dr. Olivia King'),
    ('Dr. William White'),
    ('Dr. Emma Harris'),
    ('Dr. Andrew Martin'),
    ('Dr. Sophia Thompson'),
    ('Dr. David Wilson'),
    ('Dr. Mia Turner'),
    ('Dr. Jacob Green'),
    ('Dr. Ava Walker'),
    ('Dr. Ethan Robinson'),
    ('Dr. Grace Hill'),
    ('Dr. Alexander Allen'),
    ('Dr. Chloe Baker'),
    ('Dr. Joseph Young'),
    ('Dr. Lily Turner'),
    ('Dr. Samuel Scott'),
    ('Dr. Harper Adams'),
    ('Dr. Daniel Clark'),
    ('Dr. Madison Mitchell'),
    ('Dr. Gabriel Turner'),
    ('Dr. Victoria Nelson'),
    ('Dr. Elijah Wright'),
    ('Dr. Zoey Rodriguez'),
    ('Dr. Caleb Torres'),
    ('Dr. Penelope Hill'),
    ('Dr. Nathan James'),
    ('Dr. Stella Wilson'),
    ('Dr. Isaac Moore'),
    ('Dr. Audrey Martinez'),
    ('Dr. Matthew Rodriguez'),
    ('Dr. Hannah Adams'),
    ('Dr. Julian Wright'),
    ('Dr. Addison Turner'),
    ('Dr. David Davis'),
    ('Dr. Natalie Smith'),
    ('Dr. Leo Lewis'),
    ('Dr. Brooklyn Foster'),
    ('Dr. Levi Turner'),
    ('Dr. Hazel Martin'),
    ('Dr. Aaron Rodriguez'),
    ('Dr. Riley Brooks'),
    ('Dr. Samuel Murphy'),
    ('Dr. Bella Thompson'),
    ('Dr. Henry Morris'),
    ('Dr. Savannah Bennett'),
    ('Dr. Jack Ross'),
    ('Dr. Claire Edwards'),
    ('Dr. Landon Gonzalez'),
    ('Dr. Nora Collins'),
    ('Dr. Eli Turner'),
    ('Dr. Ava Hughes'),
    ('Dr. Jonathan Ross'),
    ('Dr. Scarlett Russell'),
    ('Dr. Josiah Sanchez'),
    ('Dr. Violet Carter'),
    ('Dr. Isaac Martinez'),
    ('Dr. Paisley Phillips'),
    ('Dr. Jeremiah Morris'),
    ('Dr. Reagan Thomas'),
    ('Dr. Luke Peterson'),
    ('Dr. Aubrey Watson'),
    ('Dr. Caleb Simmons'),
    ('Dr. Maya Cooper'),
    ('Dr. Julian Reed'),
    ('Dr. Ellie Foster'),
    ('Dr. Gabriel Diaz'),
    ('Dr. Clara Powell'),
    ('Dr. Dominic Jenkins'),
    ('Dr. Aurora Barnes'),
    ('Dr. Colton Russell'),
    ('Dr. Eva Coleman'),
    ('Dr. Micah Watson'),
    ('Dr. Naomi Carter'),
    ('Dr. Eliana Bennett'),
    ('Dr. Vincent Peterson'),
    ('Dr. Adeline Turner'),
    ('Dr. Roman Murphy'),
    ('Dr. Clara Diaz');

INSERT INTO locations (doctor_id, latitude, longitude, distance)
VALUES 
    (1, 37.7749, -122.4194, 500),
    (2, 34.0522, -118.2437, 800),
    (3, 41.8781, -87.6298, 1200),
    (4, 29.7604, -95.3698, 1500),
    (5, 40.7128, -74.0060, 2000),
    (1, 37.7749, -122.4194, 600),
    (2, 34.0522, -118.2437, 900),
    (3, 41.8781, -87.6298, 1100),
    (4, 29.7604, -95.3698, 1400),
    (5, 40.7128, -74.0060, 1800);